      version: '3.8'

      x-common: &common
        networks:
          - mgpt-network
        restart: unless-stopped
        env_file: .env
      
      services:
        bot:
          container_name: maslakgpt_bot
          build:
            context: ./
          environment:
            MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@maslakgpt_storage:27017/maslakgptsessions
          <<: *common

        storage:
          image: mongo
          container_name: maslakgpt_storage
          ports:
            - "127.0.0.1:27017:27017"
          volumes:
            - mgpt-mongo-storage:/data/db
          <<: *common  
      networks:
        mgpt-network:
          driver: bridge

      volumes:
        mgpt-mongo-storage: